// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/alireza-mf/go-ecommerce/controllers"
	"github.com/alireza-mf/go-ecommerce/repositories"
	"github.com/alireza-mf/go-ecommerce/services"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func initUserAPI(db *mongo.Database) controllers.UserController {
	userRepository := repositories.ProvideUserRepository(db)
	userService := services.ProvideUserService(userRepository)
	userController := controllers.ProvideUserController(userService)
	return userController
}

func initProductAPI(db *mongo.Database) controllers.ProductController {
	productRepository := repositories.ProvideProductRepository(db)
	productService := services.ProvideProductService(productRepository)
	productController := controllers.ProvideProductController(productService)
	return productController
}
